// <auto-generated />
using System;
using EduTrip.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduTrip.Migrations
{
    [DbContext(typeof(EduTripContext))]
    [Migration("20260510101001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduTrip.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AvailabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Confirmed");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StudentRating")
                        .HasColumnType("int");

                    b.Property<string>("StudentReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Bookings__3214EC07268730CB");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("MentorId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "OrderId" }, "UQ__Bookings__C3905BCE15DF9555")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EduTrip.Models.MentorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__MentorAv__3214EC072DB0C437");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorAvailability", (string)null);
                });

            modelBuilder.Entity("EduTrip.Models.MentorEarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CommissionRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(70.00m);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MentorShare")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidOutAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PayoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PlatformShare")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__MentorEa__3214EC078E938174");

                    b.HasIndex("MentorId");

                    b.HasIndex("PayoutId");

                    b.HasIndex(new[] { "OrderId" }, "UQ__MentorEa__C3905BCE0D568466")
                        .IsUnique();

                    b.ToTable("MentorEarnings");
                });

            modelBuilder.Entity("EduTrip.Models.MentorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Specialties")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__MentorPr__3214EC0786413712");

                    b.HasIndex(new[] { "UserId" }, "UQ__MentorPr__1788CC4DC2374744")
                        .IsUnique();

                    b.ToTable("MentorProfiles");
                });

            modelBuilder.Entity("EduTrip.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC07976C54B5");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EduTrip.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("EGP");

                    b.Property<Guid?>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC07DD3A633A");

                    b.HasIndex("MentorId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EduTrip.Models.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("HasContentAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPriorityBooking")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MentorshipCredits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Packages__3214EC07BCB7CBFA");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("EduTrip.Models.PackageEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RemainingCredits")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__PackageE__3214EC07BE1B19FC");

                    b.HasIndex("PackageId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "OrderId" }, "UQ__PackageE__C3905BCE334C942F")
                        .IsUnique();

                    b.ToTable("PackageEnrollments");
                });

            modelBuilder.Entity("EduTrip.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Initiated");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC07161BD20F");

                    b.HasIndex(new[] { "OrderId" }, "UQ__Payments__C3905BCE99F9616D")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EduTrip.Models.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("EGP");

                    b.Property<Guid?>("InitiatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Payouts__3214EC073AEA5EE0");

                    b.HasIndex("InitiatedBy");

                    b.HasIndex("MentorId");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("EduTrip.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TurnaroundDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Services__3214EC072A935A90");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("EduTrip.Models.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AssignedMentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DeliverableUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__ServiceO__3214EC073FE4EB5A");

                    b.HasIndex("AssignedMentorId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "OrderId" }, "UQ__ServiceO__C3905BCE34BE36F0")
                        .IsUnique();

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("EduTrip.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Subscrip__3214EC07B08D834C");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("EduTrip.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AccountTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07CA3576CE");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340023F999")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduTrip.Models.Booking", b =>
                {
                    b.HasOne("EduTrip.Models.MentorAvailability", "Availability")
                        .WithMany("Bookings")
                        .HasForeignKey("AvailabilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_MentorAvailability");

                    b.HasOne("EduTrip.Models.MentorProfile", "Mentor")
                        .WithMany("Bookings")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_MentorProfiles");

                    b.HasOne("EduTrip.Models.Order", "Order")
                        .WithOne("Booking")
                        .HasForeignKey("EduTrip.Models.Booking", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Orders");

                    b.HasOne("EduTrip.Models.User", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_StudentUsers");

                    b.Navigation("Availability");

                    b.Navigation("Mentor");

                    b.Navigation("Order");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTrip.Models.MentorAvailability", b =>
                {
                    b.HasOne("EduTrip.Models.MentorProfile", "Mentor")
                        .WithMany("MentorAvailabilities")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MentorAvailability_MentorProfiles");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("EduTrip.Models.MentorEarning", b =>
                {
                    b.HasOne("EduTrip.Models.MentorProfile", "Mentor")
                        .WithMany("MentorEarnings")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK_MentorEarnings_MentorProfiles");

                    b.HasOne("EduTrip.Models.Order", "Order")
                        .WithOne("MentorEarning")
                        .HasForeignKey("EduTrip.Models.MentorEarning", "OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_MentorEarnings_Orders");

                    b.HasOne("EduTrip.Models.Payout", "Payout")
                        .WithMany("MentorEarnings")
                        .HasForeignKey("PayoutId")
                        .HasConstraintName("FK_MentorEarnings_Payouts");

                    b.Navigation("Mentor");

                    b.Navigation("Order");

                    b.Navigation("Payout");
                });

            modelBuilder.Entity("EduTrip.Models.MentorProfile", b =>
                {
                    b.HasOne("EduTrip.Models.User", "User")
                        .WithOne("MentorProfile")
                        .HasForeignKey("EduTrip.Models.MentorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MentorProfiles_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTrip.Models.Notification", b =>
                {
                    b.HasOne("EduTrip.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTrip.Models.Order", b =>
                {
                    b.HasOne("EduTrip.Models.MentorProfile", "Mentor")
                        .WithMany("Orders")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("FK_Orders_MentorProfiles");

                    b.HasOne("EduTrip.Models.Package", "Package")
                        .WithMany("Orders")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_Orders_Packages");

                    b.HasOne("EduTrip.Models.Service", "Service")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_Orders_Services");

                    b.HasOne("EduTrip.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("Mentor");

                    b.Navigation("Package");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTrip.Models.PackageEnrollment", b =>
                {
                    b.HasOne("EduTrip.Models.Order", "Order")
                        .WithOne("PackageEnrollment")
                        .HasForeignKey("EduTrip.Models.PackageEnrollment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PackageEnrollments_Orders");

                    b.HasOne("EduTrip.Models.Package", "Package")
                        .WithMany("PackageEnrollments")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK_PackageEnrollments_Packages");

                    b.HasOne("EduTrip.Models.User", "Student")
                        .WithMany("PackageEnrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_PackageEnrollments_StudentUsers");

                    b.Navigation("Order");

                    b.Navigation("Package");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTrip.Models.Payment", b =>
                {
                    b.HasOne("EduTrip.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("EduTrip.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EduTrip.Models.Payout", b =>
                {
                    b.HasOne("EduTrip.Models.User", "InitiatedByNavigation")
                        .WithMany("Payouts")
                        .HasForeignKey("InitiatedBy")
                        .HasConstraintName("FK_Payouts_InitiatedByUsers");

                    b.HasOne("EduTrip.Models.MentorProfile", "Mentor")
                        .WithMany("Payouts")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK_Payouts_MentorProfiles");

                    b.Navigation("InitiatedByNavigation");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("EduTrip.Models.ServiceOrder", b =>
                {
                    b.HasOne("EduTrip.Models.MentorProfile", "AssignedMentor")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("AssignedMentorId")
                        .HasConstraintName("FK_ServiceOrders_AssignedMentorProfiles");

                    b.HasOne("EduTrip.Models.Order", "Order")
                        .WithOne("ServiceOrder")
                        .HasForeignKey("EduTrip.Models.ServiceOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceOrders_Orders");

                    b.HasOne("EduTrip.Models.Service", "Service")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_ServiceOrders_Services");

                    b.HasOne("EduTrip.Models.User", "Student")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_ServiceOrders_StudentUsers");

                    b.Navigation("AssignedMentor");

                    b.Navigation("Order");

                    b.Navigation("Service");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTrip.Models.Subscription", b =>
                {
                    b.HasOne("EduTrip.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Subscriptions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTrip.Models.MentorAvailability", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EduTrip.Models.MentorProfile", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MentorAvailabilities");

                    b.Navigation("MentorEarnings");

                    b.Navigation("Orders");

                    b.Navigation("Payouts");

                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("EduTrip.Models.Order", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("MentorEarning");

                    b.Navigation("PackageEnrollment");

                    b.Navigation("Payment");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("EduTrip.Models.Package", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PackageEnrollments");
                });

            modelBuilder.Entity("EduTrip.Models.Payout", b =>
                {
                    b.Navigation("MentorEarnings");
                });

            modelBuilder.Entity("EduTrip.Models.Service", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("EduTrip.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MentorProfile");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("PackageEnrollments");

                    b.Navigation("Payouts");

                    b.Navigation("ServiceOrders");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
